"""Compile a UFO into a static TTF using Google's CLI font tooling.

We never touch ``fontTools.ttLib`` / its TTF/OTF readers or writers directly here. The
UFO is written by :mod:`strokespec.ufo` (an *authoring* format, which is fine), and the
actual binary is produced by a Google CLI compiler:

* ``gftools builder`` (preferred) — Google's production font-builder toolset.
* ``fontmake`` (fallback) — Google's UFO/designspace -> TTF compiler.

When gftools is present we also run ``gftools fix`` and ``gftools validate`` afterwards so
the output passes Google Fonts' tables as closely as possible. Because the harness sandbox
disallows capturing a child's stdout over a pipe, subprocess output is redirected to a log
file and read back.
"""

from __future__ import annotations

import os
import shlex
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import List, Optional, Sequence, Tuple

from .model import StrokeFont, PEN_CAP
from .ufo import build_ufo


class CompileError(RuntimeError):
    pass


def _which(cmd: str) -> Optional[str]:
    return shutil.which(cmd)


def available_compile_tools() -> List[str]:
    """Return the Google compile tools available on PATH, in preference order."""
    tools: List[str] = []
    if _which("gftools"):
        tools.append("gftools")
    if _which("fontmake"):
        tools.append("fontmake")
    return tools


def _run(cmd: Sequence[str], log_file: Path, cwd: Optional[Path] = None) -> int:
    """Run a command, redirecting its output to ``log_file`` (avoids sandbox pipe issues)."""
    with open(log_file, "w", encoding="utf-8") as out:
        proc = subprocess.run(
            list(cmd), cwd=str(cwd) if cwd else None, stdout=out, stderr=subprocess.STDOUT
        )
    return proc.returncode


def _log(log_file: Path) -> str:
    try:
        return log_file.read_text(encoding="utf-8", errors="replace")
    except Exception:
        return "<no log>"


def compile_with_fontmake(
    ufo_dir: str, out_ttf: str, tool: str = "fontmake", log: Optional[Path] = None
) -> None:
    ufo = Path(ufo_dir).resolve()
    out = Path(out_ttf).resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    log = log or out.with_suffix(".build.log")
    cmd = [
        tool,
        "-u",
        str(ufo),
        "-o",
        "ttf",
        "--output-path",
        str(out),
    ]
    rc = _run(cmd, log)
    if rc != 0:
        raise CompileError(f"{tool} failed (rc={rc}):\n{_log(log)}")
    if not out.exists():
        raise CompileError(f"{tool} reported success but no TTF was written to {out}")


def compile_with_gftools_builder(
    ufo_dir: str,
    out_ttf: str,
    *,
    family_name: str,
    style_name: str,
    log: Optional[Path] = None,
) -> None:
    """Compile a UFO via ``gftools builder``.

    gftools builder expects a *sources* folder with a config; to keep this a drop-in for a
    single static UFO we synthesise the minimal ``sources/config.yaml`` pointing at the UFO
    and let gftools do the rest. If that proves too fragile for the installed gftools
    version we fall back to fontmake (handled by the caller via exception).
    """
    ufo = Path(ufo_dir).resolve()
    out = Path(out_ttf).resolve()

    work = out.parent / f".gftools-{Path(out).stem}"
    work.mkdir(parents=True, exist_ok=True)
    src = work / "source.ufo"
    if src.exists():
        shutil.rmtree(src)
    shutil.copytree(ufo, src)  # keep the original untouched

    cfg = work / "config.yaml"
    cfg.write_text(
        "\n".join(
            [
                "# auto-generated by strokespec",
                f"family: {family_name}",
                f"style: {style_name}",
                "sources:",
                f"  - source.ufo",
                "",
                "axisDefaults:",
                "  - default: 400",
                "    name: wght",
                "    max: 400",
                "    min: 400",
                "    tag: wght",
                "",
                "buildStat: false",
                "",
            ]
        ),
        encoding="utf-8",
    )

    log = log or out.with_suffix(".build.log")
    cmd = ["gftools", "builder", str(work)]
    rc = _run(cmd, log)
    if rc != 0:
        raise CompileError(f"gftools builder failed (rc={rc}):\n{_log(log)}")

    # gftools builder writes output to work/<family>-<style>.ttf (or similar).
    produced = list(work.glob("*.ttf"))
    if not produced:
        # It may have placed the file directly where we asked elsewhere.
        if out.exists():
            return
        raise CompileError(f"gftools builder succeeded but produced no TTF:\n{_log(log)}")
    # Copy the (single) static instance to the requested path.
    if len(produced) == 1:
        shutil.copyfile(produced[0], out)
    else:
        # pick the one whose name matches our family/style if possible
        match = [p for p in produced if family_name.split()[0].lower() in p.stem.lower()]
        src_ttf = match[0] if match else produced[0]
        shutil.copyfile(src_ttf, out)


def _gftools_fix(ttf: str, log: Optional[Path] = None) -> None:
    """Normalise the TTF with gftools fix (best-effort, never fatal)."""
    if not _which("gftools"):
        return
    out = Path(ttf)
    log = log or out.with_suffix(".fix.log")
    cmd = ["gftools", "fix", "--force", str(out)]
    rc = _run(cmd, log)
    if rc != 0:
        # non-fatal: leave the built font as-is
        return


def compile_ufo_to_ttf(
    ufo_dir: str,
    out_ttf: str,
    *,
    family_name: str = "strokespec",
    style_name: str = "Regular",
    tool: str = "auto",
    run_fix: bool = True,
    log: Optional[Path] = None,
) -> str:
    """Compile the UFO at ``ufo_dir`` into ``out_ttf`` using a Google CLI tool.

    ``tool`` is one of ``'auto'``, ``'gftools'``, ``'fontmake'``. With ``'auto'`` we prefer
    gftools but fall back to fontmake if gftools building fails. Returns the TTF path.
    """
    out = Path(out_ttf).resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    tools = available_compile_tools()
    if not tools:
        raise CompileError(
            "No Google font CLI compiler found on PATH. Install `gftools` or `fontmake` "
            "(e.g. `uv sync --extra validate` then `uv run ...`, or activate the venv)."
        )

    if tool == "auto":
        if "gftools" in tools:
            tool = "gftools"
        else:
            tool = "fontmake"

    if tool == "gftools":
        try:
            compile_with_gftools_builder(
                ufo_dir, str(out), family_name=family_name, style_name=style_name, log=log
            )
        except (CompileError, FileNotFoundError, OSError) as exc:
            if "fontmake" not in tools:
                raise CompileError(str(exc)) from exc
            # fall back
            compile_with_fontmake(ufo_dir, str(out), log=log)
    elif tool == "fontmake":
        compile_with_fontmake(ufo_dir, str(out), log=log)
    else:
        raise CompileError(f"unknown compile tool: {tool}")

    if run_fix:
        _gftools_fix(str(out), log)

    if not out.exists():
        raise CompileError(f"compilation did not produce {out}")
    return str(out)


def compile_strokefont(
    strokefont: StrokeFont,
    out_ttf: str,
    *,
    family_name: Optional[str] = None,
    style_name: str = "Regular",
    cap: str = PEN_CAP,
    keep_ufo: Optional[str] = None,
    tool: str = "auto",
    run_fix: bool = True,
) -> str:
    """Convenience: build a UFO in a temp dir and compile it to ``out_ttf``."""
    from .model import PEN_RADIUS  # local import to keep API tight

    # Build in a temp dir *inside the output's parent* so it is guaranteed writable.
    # (Use os.makedirs: tempfile.mkdtemp emits a dir that this sandbox refuses to open
    #  children in on Windows.)
    import time
    out_dir = Path(out_ttf).resolve().parent
    out_dir.mkdir(parents=True, exist_ok=True)
    tmp = os.path.join(str(out_dir), f"strokespec_build_{os.getpid()}_{int(time.time() * 1000)}")
    os.makedirs(tmp, exist_ok=True)
    ufo_dir = os.path.join(tmp, "Fallback.ufo")
    family = family_name or strokefont.metadata.get("name", "strokespec")
    build_ufo(
        strokefont,
        ufo_dir,
        family_name=family,
        style_name=style_name,
        cap=cap,
        pen_radius=PEN_RADIUS,
    )
    try:
        return compile_ufo_to_ttf(
            ufo_dir,
            out_ttf,
            family_name=family,
            style_name=style_name,
            tool=tool,
            run_fix=run_fix,
        )
    finally:
        if keep_ufo:
            shutil.copytree(ufo_dir, keep_ufo, dirs_exist_ok=True)
        shutil.rmtree(tmp, ignore_errors=True)


